// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/04       [336388]
Creator        : mukul
Date           : Mon Mar 25 21:06:42 2013
Host           : Darwin proof.cern.ch 12.2.0 Darwin Kernel Version 12.2.0: Sat Aug 25 00:48:52 PDT 2012; root:xnu-2050.18.24~1/RELEASE_X86_64 x86_64
Dir            : /Users/mukul/Dropbox/Rice/2012 Fall/Thesis/squark-search
Training events: 10523
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "52" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
AdaBoostBeta: "5.000000e-01" [Parameter for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
nCuts: "20" [Number of steps during node cut optimisation]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "4" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "10523" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
m3a                           m3a                           m3a                           m3a                                                             'F'    [61.7712593079,2928.61328125]
m2a                           m2a                           m2a                           m2a                                                             'F'    [11.4315071106,2440.0534668]
angles_b_a                    angles_b_a                    angles_b_a                    angles_b_a                                                      'F'    [0.000190999999177,3.14150190353]
angles_j1_a                   angles_j1_a                   angles_j1_a                   angles_j1_a                                                     'F'    [0.000254000013229,3.14147901535]
angles_j2_a                   angles_j2_a                   angles_j2_a                   angles_j2_a                                                     'F'    [0.000342999992426,3.14136910439]
m3b                           m3b                           m3b                           m3b                                                             'F'    [28.1598796844,1966.14428711]
m2b                           m2b                           m2b                           m2b                                                             'F'    [7.32476902008,1212.12280273]
angles_b_b                    angles_b_b                    angles_b_b                    angles_b_b                                                      'F'    [0.000237000000197,3.1413230896]
angles_j1_b                   angles_j1_b                   angles_j1_b                   angles_j1_b                                                     'F'    [0.000334999989718,3.1413640976]
angles_j2_b                   angles_j2_b                   angles_j2_b                   angles_j2_b                                                     'F'    [0.000476999994135,3.14158201218]
mT_b                          mT_b                          mT_b                          mT_b                                                            'F'    [0.00356399989687,8671833]
eT_missing                    eT_missing                    eT_missing                    eT_missing                                                      'F'    [5.07506513596,1655.27246094]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "m3a", "m2a", "angles_b_a", "angles_j1_a", "angles_j2_a", "m3b", "m2b", "angles_b_b", "angles_j1_b", "angles_j2_b", "mT_b", "eT_missing" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 61.7712593078613;
      fVmax[0] = 2928.61328125;
      fVmin[1] = 11.4315071105957;
      fVmax[1] = 2440.05346679688;
      fVmin[2] = 0.000190999999176711;
      fVmax[2] = 3.14150190353394;
      fVmin[3] = 0.000254000013228506;
      fVmax[3] = 3.14147901535034;
      fVmin[4] = 0.000342999992426485;
      fVmax[4] = 3.14136910438538;
      fVmin[5] = 28.1598796844482;
      fVmax[5] = 1966.14428710938;
      fVmin[6] = 7.32476902008057;
      fVmax[6] = 1212.12280273438;
      fVmin[7] = 0.00023700000019744;
      fVmax[7] = 3.14132308959961;
      fVmin[8] = 0.000334999989718199;
      fVmax[8] = 3.14136409759521;
      fVmin[9] = 0.00047699999413453;
      fVmax[9] = 3.14158201217651;
      fVmin[10] = 0.00356399989686906;
      fVmax[10] = 8671833;
      fVmin[11] = 5.07506513595581;
      fVmax[11] = 1655.2724609375;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.997007475537889);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343985,-99) , 
1, 92.9028, 1, 0, 0.475442,-99) , 
NN(
0, 
0, 
-1, 204.18, 1, -1, 0.148604,-99) , 
0, 275.436, 1, 0, 0.297406,-99) , 
NN(
0, 
0, 
-1, 198.288, 1, -1, 0.0859177,-99) , 
11, 319.398, 0, 0, 0.130856,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.576706);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544272,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344825,-99) , 
5, 212.73, 1, 0, 0.480955,-99) , 
NN(
0, 
0, 
-1, 375.586, 0, -1, 0.253664,-99) , 
0, 275.436, 1, 0, 0.376855,-99) , 
NN(
0, 
0, 
-1, 198.288, 1, -1, 0.163406,-99) , 
11, 240.818, 0, 0, 0.253727,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.439785);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458825,-99) , 
5, 127.289, 1, 0, 0.493654,-99) , 
NN(
0, 
0, 
-1, 98.9927, 0, -1, 0.0699719,-99) , 
11, 108.644, 0, 0, 0.450633,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379767,-99) , 
7, 1.04592, 0, 0, 0.514687,-99) , 
NN(
0, 
0, 
-1, 78746.8, 0, -1, 0.197624,-99) , 
11, 397.979, 0, 0, 0.253251,-99) , 
0, 198.288, 1, 0, 0.324484,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.301583);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 66141.5, 0, 1, 0.572985,-99) , 
NN(
0, 
0, 
-1, 308.186, 0, -1, 0.354228,-99) , 
0, 178.957, 1, 0, 0.4176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.393461,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.28154);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 83.1843, 1, 1, 0.616124,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369925,-99) , 
10, 65941.6, 0, 0, 0.423023,-99) , 
11, 457.862, 0, 0, 0.4471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.424118,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.214548);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385192,-99) , 
6, 89.1531, 1, 0, 0.518171,-99) , 
NN(
0, 
0, 
-1, 282.017, 1, -1, 0.380844,-99) , 
5, 212.73, 1, 0, 0.467718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.446213,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.17862);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380518,-99) , 
11, 149.723, 0, 0, 0.512724,-99) , 
NN(
0, 
0, 
-1, 1.19694, 0, -1, 0.406107,-99) , 
2, 1.64564, 0, 0, 0.467551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.447907,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.182408);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426594,-99) , 
0, 213.868, 1, 0, 0.518396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335319,-99) , 
11, 281.768, 0, 0, 0.416294,-99) , 
1, 120.233, 1, 0, 0.469015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.450778,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.157562);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316148,-99) , 
3, 0.449062, 0, 0, 0.49539,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391471,-99) , 
5, 120.445, 1, 0, 0.41246,-99) , 
7, 1.49599, 0, 0, 0.457303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.440869,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.146729);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449929,-99) , 
1, 45.2651, 1, 0, 0.458613,-99) , 
NN(
0, 
0, 
-1, 268.101, 0, -1, 0.260517,-99) , 
0, 764.885, 1, 0, 0.453127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.437937,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0826904);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484127,-99) , 
11, 607.552, 0, 0, 0.490846,-99) , 
NN(
0, 
0, 
-1, 268.101, 0, -1, 0.289759,-99) , 
0, 764.885, 1, 0, 0.485427,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.470183,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.089558);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453788,-99) , 
6, 122.067, 1, 0, 0.509824,-99) , 
NN(
0, 
0, 
-1, 268.101, 0, -1, 0.307068,-99) , 
0, 764.885, 1, 0, 0.504443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.489204,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0642135);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490292,-99) , 
11, 607.552, 0, 0, 0.495293,-99) , 
NN(
0, 
0, 
-1, 268.101, 0, -1, 0.326445,-99) , 
0, 764.885, 1, 0, 0.490877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.476655,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0552144);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 236.81, 0, 1, 0.510056,-99) , 
NN(
0, 
0, 
-1, 268.101, 0, -1, 0.340719,-99) , 
0, 764.885, 1, 0, 0.505672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.491462,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.107774);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 232.104, 0, 1, 0.516452,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440315,-99) , 
5, 138.181, 1, 0, 0.466318,-99) , 
1, 120.233, 1, 0, 0.492581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.4791,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.106167);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476447,-99) , 
4, 1.94518, 1, 0, 0.49598,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348774,-99) , 
9, 1.95186, 1, 0, 0.426905,-99) , 
3, 1.0474, 0, 0, 0.487499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.474803,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0784201);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410796,-99) , 
8, 0.149908, 0, 0, 0.508527,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527872,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373258,-99) , 
9, 1.95186, 1, 0, 0.432435,-99) , 
3, 1.0474, 0, 0, 0.499257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.486874,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0779027);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665698,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491922,-99) , 
4, 2.09558, 1, 0, 0.542337,-99) , 
NN(
0, 
0, 
-1, 101.488, 0, -1, 0.476215,-99) , 
11, 457.862, 0, 0, 0.484573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.47299,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0799843);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.691241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.285436,-99) , 
1, 229.226, 1, 0, 0.596075,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.652382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487952,-99) , 
6, 29.1699, 1, 0, 0.49784,-99) , 
6, 236.81, 0, 0, 0.502617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.491035,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.104652);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.60776, 1, 1, 0.677954,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.300936,-99) , 
11, 115.742, 0, 0, 0.516351,-99) , 
11, 757.215, 0, 0, 0.518871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.507356,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0523261);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.60776, 1, 1, 0.654693,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323399,-99) , 
11, 115.742, 0, 0, 0.493265,-99) , 
11, 757.215, 0, 0, 0.495747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.485263,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0603532);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.755078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497327,-99) , 
4, 2.60776, 1, 0, 0.64277,-99) , 
NN(
0, 
0, 
-1, 115.742, 0, -1, 0.481689,-99) , 
11, 757.215, 0, 0, 0.484148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.474163,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0387164);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497896,-99) , 
6, 236.81, 0, 0, 0.502113,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.103772,-99) , 
11, 268.101, 0, 0, 0.375964,-99) , 
0, 764.885, 1, 0, 0.49897,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.488972,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0666342);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466167,-99) , 
5, 305.015, 1, 0, 0.510884,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.107429,-99) , 
11, 268.101, 0, 0, 0.372091,-99) , 
0, 764.885, 1, 0, 0.507444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.497465,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0436437);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494663,-99) , 
6, 236.81, 0, 0, 0.499268,-99) , 
NN(
0, 
0, 
-1, 268.101, 0, -1, 0.365332,-99) , 
0, 764.885, 1, 0, 0.495972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.486524,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.042183);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 282.101, 0, 1, 0.509153,-99) , 
NN(
0, 
0, 
-1, 268.101, 0, -1, 0.37551,-99) , 
0, 764.885, 1, 0, 0.505882,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.496446,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0443587);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.60776, 1, 1, 0.642784,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344683,-99) , 
11, 115.742, 0, 0, 0.493586,-99) , 
11, 757.215, 0, 0, 0.495852,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.48679,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0533037);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.736614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499919,-99) , 
4, 2.60776, 1, 0, 0.632535,-99) , 
NN(
0, 
0, 
-1, 115.742, 0, -1, 0.483752,-99) , 
11, 757.215, 0, 0, 0.485999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.477305,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0471375);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49386,-99) , 
1, 282.101, 0, 0, 0.501872,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510564,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.124534,-99) , 
11, 268.101, 0, 0, 0.387675,-99) , 
0, 764.885, 1, 0, 0.499096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.490393,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0420896);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.299388, 1, 1, 0.510135,-99) , 
NN(
0, 
0, 
-1, 1.19825, 0, -1, 0.382694,-99) , 
0, 764.885, 1, 0, 0.507053,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.498411,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0453427);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496601,-99) , 
9, 2.99173, 0, 0, 0.500769,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.261352,-99) , 
4, 0.876791, 0, 0, 0.420406,-99) , 
3, 0.449096, 0, 0, 0.497039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.488739,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.070367);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482413,-99) , 
2, 1.19688, 0, 0, 0.511099,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.270199,-99) , 
4, 0.876791, 0, 0, 0.420055,-99) , 
3, 0.449096, 0, 0, 0.506902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.49862,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0510794);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494782,-99) , 
8, 2.3935, 0, 0, 0.503705,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.284297,-99) , 
4, 0.876791, 0, 0, 0.419501,-99) , 
3, 0.449096, 0, 0, 0.499858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.491959,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0568837);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.6926, 0, 1, 0.51483,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407328,-99) , 
9, 1.95186, 1, 0, 0.452798,-99) , 
3, 1.0474, 0, 0, 0.507413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.499589,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0692629);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.775797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397099,-99) , 
8, 1.04688, 0, 0, 0.564323,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467592,-99) , 
9, 1.43336, 0, 0, 0.490884,-99) , 
9, 0.150894, 1, 0, 0.495279,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.487847,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0736856);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.809526,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441319,-99) , 
8, 1.19627, 0, 0, 0.567179,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465733,-99) , 
8, 1.49606, 1, 0, 0.48795,-99) , 
9, 0.150894, 1, 0, 0.492641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.485487,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0598694);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.905832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493626,-99) , 
8, 1.79385, 0, 0, 0.573789,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535143,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482498,-99) , 
7, 0.299388, 1, 0, 0.488215,-99) , 
9, 0.150894, 1, 0, 0.493239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.486322,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0625752);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.760633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446518,-99) , 
8, 1.04688, 0, 0, 0.583352,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513534,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475802,-99) , 
7, 1.19684, 0, 0, 0.499928,-99) , 
9, 0.150894, 1, 0, 0.504808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.497928,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0313566);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.79385, 0, 1, 0.58614,-99) , 
NN(
0, 
0, 
-1, 0.449096, 0, -1, 0.495563,-99) , 
9, 0.150894, 1, 0, 0.500822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.494197,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0411099);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.79385, 0, 1, 0.578513,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507173,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427803,-99) , 
3, 0.449096, 0, 0, 0.503402,-99) , 
9, 0.150894, 1, 0, 0.507753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.501138,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.032175);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.88784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496731,-99) , 
8, 1.79385, 0, 0, 0.568458,-99) , 
NN(
0, 
0, 
-1, 2.99175, 1, -1, 0.4941,-99) , 
9, 0.150894, 1, 0, 0.498395,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.492031,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0404806);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.70654, 0, 1, 0.510281,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.306702,-99) , 
2, 1.78945, 1, 0, 0.434108,-99) , 
7, 2.99175, 1, 0, 0.50627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.499905,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0347946);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.60776, 1, 1, 0.631169,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365873,-99) , 
11, 115.742, 0, 0, 0.494472,-99) , 
11, 757.215, 0, 0, 0.49656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.490439,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0417503);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.725195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495548,-99) , 
4, 2.60776, 1, 0, 0.623032,-99) , 
NN(
0, 
0, 
-1, 115.742, 0, -1, 0.486745,-99) , 
11, 757.215, 0, 0, 0.488818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.482894,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.050508);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.882238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497323,-99) , 
8, 1.79385, 0, 0, 0.566522,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482871,-99) , 
2, 2.24403, 0, 0, 0.49496,-99) , 
9, 0.150894, 1, 0, 0.499077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.49315,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0346934);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.79385, 0, 1, 0.574876,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494903,-99) , 
6, 236.81, 0, 0, 0.498127,-99) , 
9, 0.150894, 1, 0, 0.502532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.496706,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0523636);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 52.0429, 1, 1, 0.568236,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315581,-99) , 
11, 105.016, 0, 0, 0.505111,-99) , 
11, 532.7, 0, 0, 0.509428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.503621,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0317231);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 52.0429, 1, 1, 0.555345,-99) , 
NN(
0, 
0, 
-1, 105.016, 0, -1, 0.492875,-99) , 
11, 532.7, 0, 0, 0.497136,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.49161,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0399396);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498157,-99) , 
7, 2.70654, 0, 0, 0.507488,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521416,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311113,-99) , 
2, 1.78945, 1, 0, 0.440888,-99) , 
7, 2.99175, 1, 0, 0.503986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.49847,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0491391);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 96798.3, 0, 1, 0.514978,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349734,-99) , 
8, 1.49803, 1, 0, 0.43834,-99) , 
7, 2.99175, 1, 0, 0.510959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.505474,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0307876);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505201,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437881,-99) , 
7, 2.99175, 1, 0, 0.501675,-99) , 
NN(
0, 
0, 
-1, 1.19825, 0, -1, 0.405668,-99) , 
0, 764.885, 1, 0, 0.499365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.49413,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0387483);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.867191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4844,-99) , 
8, 1.79385, 0, 0, 0.55005,-99) , 
NN(
0, 
0, 
-1, 0.897779, 0, -1, 0.489368,-99) , 
9, 0.150894, 1, 0, 0.492824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 83.6559, 0, 0, 0.487734,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
