// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/04       [336388]
Creator        : mukul
Date           : Mon Mar 25 01:36:16 2013
Host           : Darwin proof.cern.ch 12.2.0 Darwin Kernel Version 12.2.0: Sat Aug 25 00:48:52 PDT 2012; root:xnu-2050.18.24~1/RELEASE_X86_64 x86_64
Dir            : /Users/mukul/Dropbox/Rice/2012 Fall/Thesis/squark-search
Training events: 3227
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "30" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
AdaBoostBeta: "5.000000e-01" [Parameter for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "150" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "20" [Number of steps during node cut optimisation]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "3227" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
m3a                           m3a                           m3a                           m3a                                                             'F'    [75.4778060913,2175.03735352]
m2a                           m2a                           m2a                           m2a                                                             'F'    [9.3214263916,2100.06665039]
angles_b_a                    angles_b_a                    angles_b_a                    angles_b_a                                                      'F'    [0.000497000000905,3.13998007774]
angles_j1_a                   angles_j1_a                   angles_j1_a                   angles_j1_a                                                     'F'    [0.00161200005095,3.14126205444]
angles_j2_a                   angles_j2_a                   angles_j2_a                   angles_j2_a                                                     'F'    [0.000898000027519,3.14096498489]
m3b                           m3b                           m3b                           m3b                                                             'F'    [28.1598796844,1308.12854004]
m2b                           m2b                           m2b                           m2b                                                             'F'    [7.32476902008,951.399108887]
angles_b_b                    angles_b_b                    angles_b_b                    angles_b_b                                                      'F'    [0.00124300003517,3.14016699791]
angles_j1_b                   angles_j1_b                   angles_j1_b                   angles_j1_b                                                     'F'    [0.000199999994948,3.14133810997]
angles_j2_b                   angles_j2_b                   angles_j2_b                   angles_j2_b                                                     'F'    [0.000136999995448,3.14090704918]
missing_eT                    missing_eT                    missing_eT                    missing_eT                                                      'F'    [5.07506513596,1337.17871094]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "m3a", "m2a", "angles_b_a", "angles_j1_a", "angles_j2_a", "m3b", "m2b", "angles_b_b", "angles_j1_b", "angles_j2_b", "missing_eT" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 75.4778060913086;
      fVmax[0] = 2175.03735351562;
      fVmin[1] = 9.32142639160156;
      fVmax[1] = 2100.06665039062;
      fVmin[2] = 0.000497000000905246;
      fVmax[2] = 3.13998007774353;
      fVmin[3] = 0.00161200005095452;
      fVmax[3] = 3.14126205444336;
      fVmin[4] = 0.000898000027518719;
      fVmax[4] = 3.1409649848938;
      fVmin[5] = 28.1598796844482;
      fVmax[5] = 1308.12854003906;
      fVmin[6] = 7.32476902008057;
      fVmax[6] = 951.399108886719;
      fVmin[7] = 0.00124300003517419;
      fVmax[7] = 3.14016699790955;
      fVmin[8] = 0.000199999994947575;
      fVmax[8] = 3.14133810997009;
      fVmin[9] = 0.000136999995447695;
      fVmax[9] = 3.14090704917908;
      fVmin[10] = 5.07506513595581;
      fVmax[10] = 1337.1787109375;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.445308936645713);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 209.328, 1, 1, 0.839564,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330565,-99) , 
1, 90.8129, 1, 0, 0.462936,-99) , 
10, 310.216, 0, 0, 0.582755,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507692,-99) , 
NN(
0, 
0, 
-1, 217.278, 1, -1, 0.182297,-99) , 
10, 385.676, 0, 0, 0.252275,-99) , 
0, 275.436, 1, 0, 0.45894,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.378698);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 209.328, 1, 1, 0.71217,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348911,-99) , 
10, 179.858, 0, 0, 0.410726,-99) , 
10, 249.469, 0, 0, 0.541956,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.266647,-99) , 
10, 266.829, 0, 0, 0.391639,-99) , 
NN(
0, 
0, 
-1, 224.973, 1, -1, 0.209788,-99) , 
7, 1.49597, 0, 0, 0.291793,-99) , 
0, 275.436, 1, 0, 0.450131,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.287069);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 245.207, 1, 1, 0.699982,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395633,-99) , 
0, 197.061, 1, 0, 0.464712,-99) , 
10, 309.148, 0, 0, 0.534905,-99) , 
NN(
0, 
0, 
-1, 1.49581, 0, -1, 0.310129,-99) , 
5, 211.013, 1, 0, 0.452231,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.245941);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.54764, 0, 1, 0.756527,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424662,-99) , 
6, 58.0323, 1, 0, 0.513365,-99) , 
10, 310.216, 0, 0, 0.583751,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614244,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450445,-99) , 
10, 327.608, 0, 0, 0.500361,-99) , 
NN(
0, 
0, 
-1, 1.94351, 0, -1, 0.327737,-99) , 
7, 1.49581, 0, 0, 0.421282,-99) , 
5, 150.062, 1, 0, 0.464632,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.171421);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 407.404, 0, 1, 0.74615,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452171,-99) , 
1, 80.2687, 1, 0, 0.533374,-99) , 
10, 298.02, 0, 0, 0.594523,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408491,-99) , 
6, 85.4709, 1, 0, 0.482411,-99) , 
NN(
0, 
0, 
-1, 1.34878, 0, -1, 0.328308,-99) , 
5, 271.963, 1, 0, 0.445605,-99) , 
0, 175.457, 1, 0, 0.48842,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.185943);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.742804,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4517,-99) , 
5, 182.841, 1, 0, 0.529584,-99) , 
10, 338.863, 0, 0, 0.575717,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442561,-99) , 
10, 430.777, 0, 0, 0.468185,-99) , 
NN(
0, 
0, 
-1, 1.19395, 0, -1, 0.332921,-99) , 
0, 461.168, 1, 0, 0.442792,-99) , 
0, 175.457, 1, 0, 0.480779,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.146289);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 453.804, 0, 1, 0.565854,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382811,-99) , 
2, 1.94351, 0, 0, 0.458869,-99) , 
7, 1.49597, 0, 0, 0.520086,-99) , 
NN(
0, 
0, 
-1, 1.19395, 0, -1, 0.367729,-99) , 
0, 475.394, 1, 0, 0.501628,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.172855);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461744,-99) , 
10, 188.721, 0, 0, 0.547156,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.310866,-99) , 
9, 2.10302, 1, 0, 0.40756,-99) , 
3, 1.19767, 0, 0, 0.51341,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545083,-99) , 
NN(
0, 
0, 
-1, 1.34878, 0, -1, 0.39993,-99) , 
5, 150.062, 1, 0, 0.43632,-99) , 
7, 1.19702, 0, 0, 0.485952,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0936796);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.832414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498471,-99) , 
1, 105.35, 1, 0, 0.609175,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462667,-99) , 
2, 2.39248, 0, 0, 0.481371,-99) , 
10, 449.11, 0, 0, 0.494773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.339691,-99) , 
1, 507.118, 1, 0, 0.487898,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0883846);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 430.777, 0, 1, 0.526099,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356477,-99) , 
9, 2.10308, 1, 0, 0.430237,-99) , 
3, 1.19767, 0, 0, 0.508374,-99) , 
NN(
0, 
0, 
-1, 118.481, 1, -1, 0.398558,-99) , 
8, 0.299356, 0, 0, 0.49752,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.116891);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.72816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434332,-99) , 
0, 289.064, 1, 0, 0.571186,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441366,-99) , 
3, 1.49487, 0, 0, 0.493971,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51503,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408725,-99) , 
5, 161.31, 1, 0, 0.445592,-99) , 
7, 1.49581, 0, 0, 0.472714,-99) , 
10, 449.11, 0, 0, 0.483818,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.168874);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.778699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485878,-99) , 
1, 110.89, 1, 0, 0.574413,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694223,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381074,-99) , 
9, 2.09822, 1, 0, 0.522713,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440472,-99) , 
9, 2.69299, 0, 0, 0.458306,-99) , 
8, 2.39353, 0, 0, 0.471323,-99) , 
10, 449.11, 0, 0, 0.482834,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.07386);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.710044,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481604,-99) , 
5, 211.013, 1, 0, 0.59253,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515143,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432595,-99) , 
5, 340.995, 1, 0, 0.50665,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51469,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.339267,-99) , 
9, 0.597227, 0, 0, 0.452785,-99) , 
8, 0.44922, 0, 0, 0.498418,-99) , 
10, 449.11, 0, 0, 0.508909,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0851383);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 289.064, 1, 1, 0.593834,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490742,-99) , 
1, 146.14, 0, 0, 0.520543,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466462,-99) , 
6, 173.85, 0, 0, 0.475535,-99) , 
7, 2.54201, 0, 0, 0.48514,-99) , 
10, 449.11, 0, 0, 0.497189,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0559404);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 105.35, 1, 1, 0.600502,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511913,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465032,-99) , 
5, 287.025, 1, 0, 0.504521,-99) , 
10, 449.11, 0, 0, 0.514208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387674,-99) , 
1, 507.118, 1, 0, 0.508729,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.061881);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601791,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618297,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494792,-99) , 
10, 449.11, 0, 0, 0.506545,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34341,-99) , 
1, 116.897, 1, 0, 0.413605,-99) , 
5, 292.06, 1, 0, 0.494528,-99) , 
6, 232.104, 0, 0, 0.49975,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0566986);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600955,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522201,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482463,-99) , 
0, 263.423, 1, 0, 0.508926,-99) , 
10, 512.543, 0, 0, 0.514401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407157,-99) , 
1, 507.118, 1, 0, 0.509791,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0887751);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.718717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471969,-99) , 
9, 2.09368, 1, 0, 0.589338,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561368,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479847,-99) , 
4, 1.94516, 1, 0, 0.500865,-99) , 
8, 2.39322, 0, 0, 0.513837,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502395,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367565,-99) , 
4, 0.566772, 0, 0, 0.455326,-99) , 
3, 1.04816, 0, 0, 0.505369,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0866021);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.7974, 1, 1, 0.59138,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481853,-99) , 
9, 1.34618, 0, 0, 0.511639,-99) , 
8, 2.39322, 0, 0, 0.523254,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393348,-99) , 
9, 2.11056, 1, 0, 0.448413,-99) , 
3, 1.04816, 0, 0, 0.512426,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.073469);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626602,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474241,-99) , 
2, 1.04699, 0, 0, 0.515549,-99) , 
10, 552.406, 0, 0, 0.521337,-99) , 
NN(
0, 
0, 
-1, 74.7796, 0, -1, 0.44988,-99) , 
3, 1.04816, 0, 0, 0.511017,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0397926);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461816,-99) , 
3, 2.61695, 1, 0, 0.567816,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498241,-99) , 
10, 512.543, 0, 0, 0.503849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414236,-99) , 
5, 454.816, 1, 0, 0.499279,-99) , 
4, 2.99144, 0, 0, 0.505941,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0666235);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595836,-99) , 
NN(
NN(
0, 
0, 
-1, 449.11, 0, 1, 0.522249,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50882,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366532,-99) , 
1, 116.897, 1, 0, 0.423124,-99) , 
5, 292.06, 1, 0, 0.509648,-99) , 
6, 232.104, 0, 0, 0.513813,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0413335);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579695,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497846,-99) , 
10, 449.11, 0, 0, 0.505608,-99) , 
NN(
0, 
0, 
-1, 1.34471, 0, -1, 0.426116,-99) , 
5, 292.06, 1, 0, 0.495539,-99) , 
6, 232.104, 0, 0, 0.499588,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0464171);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486829,-99) , 
8, 2.09497, 1, 0, 0.54706,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399376,-99) , 
5, 454.816, 1, 0, 0.50077,-99) , 
7, 2.54228, 0, 0, 0.511063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424635,-99) , 
1, 507.118, 1, 0, 0.507347,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0568285);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.49894, 0, 1, 0.565737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481541,-99) , 
8, 2.09497, 1, 0, 0.535114,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552872,-99) , 
NN(
0, 
0, 
-1, 0.299258, 0, -1, 0.481155,-99) , 
4, 2.99144, 0, 0, 0.489317,-99) , 
7, 2.54228, 0, 0, 0.499365,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0866092);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.729004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479923,-99) , 
8, 1.47428, 0, 0, 0.563502,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486204,-99) , 
8, 0.70562, 1, 0, 0.500204,-99) , 
9, 0.747939, 1, 0, 0.513734,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555332,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492562,-99) , 
7, 1.49288, 0, 0, 0.523289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375791,-99) , 
9, 0.597227, 0, 0, 0.469605,-99) , 
8, 0.448934, 0, 0, 0.507091,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.10877);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.37195, 0, 1, 0.545984,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.698324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462583,-99) , 
8, 1.35129, 1, 0, 0.499646,-99) , 
9, 2.09398, 1, 0, 0.52959,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565087,-99) , 
NN(
0, 
0, 
-1, 0.509593, 0, -1, 0.432008,-99) , 
9, 1.18898, 0, 0, 0.477644,-99) , 
8, 0.448934, 0, 0, 0.521784,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0985189);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.712557,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471117,-99) , 
4, 2.39333, 0, 0, 0.508181,-99) , 
9, 1.05464, 1, 0, 0.537919,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.668145,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407065,-99) , 
2, 2.69148, 1, 0, 0.482177,-99) , 
9, 2.54267, 0, 0, 0.497914,-99) , 
8, 1.79514, 0, 0, 0.51383,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.113746);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.691963,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532082,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406696,-99) , 
0, 480.005, 1, 0, 0.516962,-99) , 
9, 1.05464, 1, 0, 0.542069,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645951,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447859,-99) , 
4, 1.94463, 1, 0, 0.468058,-99) , 
9, 2.54267, 0, 0, 0.482912,-99) , 
8, 1.79514, 0, 0, 0.506397,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0489062);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570762,-99) , 
NN(
NN(
0, 
0, 
-1, 2.99144, 0, 1, 0.514571,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398647,-99) , 
7, 0.797999, 1, 0, 0.472787,-99) , 
7, 1.19702, 0, 0, 0.499666,-99) , 
9, 2.99135, 0, 0, 0.50354,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
